# -*- coding: utf-8 -*-
"""Associate Rule Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xCaW_CEq4V3sk-jFzS1DcwiPyaN96gDL

**Aprior Algorithm**
"""

pip install mlxtend

import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

dataset = [
    ['Milk', 'Bread', 'Eggs'],
    ['Milk', 'Bread'],
    ['Milk', 'Diapers', 'Beer', 'Eggs'],
    ['Bread', 'Diapers', 'Beer'],
    ['Milk', 'Bread', 'Diapers', 'Beer'],
]

# Convert dataset into one-hot encoded DataFrame
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

print("One-hot encoded dataset:")
print(df)

#apply aprior algorithm
frequent_itemsets = apriori(df, min_support=0.4, use_colnames=True)

print("\nFrequent Itemsets:")
print(frequent_itemsets)

rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)

print("\nAssociation Rules:")
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])

"""**FP-Growth**"""

from mlxtend.frequent_patterns import fpgrowth, association_rules
from mlxtend.preprocessing import TransactionEncoder

#sample dataset
dataset = [
    ['Milk', 'Bread', 'Eggs'],
    ['Milk', 'Bread'],
    ['Milk', 'Diapers', 'Beer', 'Eggs'],
    ['Bread', 'Diapers', 'Beer'],
    ['Milk', 'Bread', 'Diapers', 'Beer'],
]

# Convert to one-hot encoding
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

print("One-hot encoded dataset:")
print(df)

#apply fp-growth
frequent_itemsets = fpgrowth(df, min_support=0.4, use_colnames=True, max_len=3)

print("\nFrequent Itemsets:")
print(frequent_itemsets)

#Generate Association Rules

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)

print("\nAssociation Rules:")
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])